name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gtest-permission
      run: chmod a+x 3_Implementation/FINAL_CROP_PRODUCTION_PROJECT/all.out 
